### ISSUE TITLE
Unit test failed

### ISSUE THREAD

**Issue by henrycaohao** [dachev/node-cld#28] opened 2016-03-07 01:05 UTC
I run unit test on node-cld, and it not pass.

<pre>throw new assert.AssertionError({
^
AssertionError: { message: 'Failed to identify language' } == null
at D:\Projects\cld\test\runner.js:12:14
at Object.module.exports.detect (D:\Projects\cld\index.js:71:14)
at D:\Projects\cld\test\runner.js:11:9
at Function._.each._.forEach (D:\projects\cld\node_modules\underscore\underscore.js:153:9)
at runCoreTests (D:\Projects\cld\test\runner.js:10:5)
at Objects.<anonymous> (D:\Projects\cld\test\runner.js:135:1)
at Module._compile (module.js:434:26)
at Object.Module._extensions..js (module.js:452:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
npm ERR! Test failed. see above for more details.</pre>

I try some languages and it can't detect although it has in data in the unit test.
`{ message: 'Failed to identify language'}`

Some languages you can try: SOMALI, IGBO, HAUSA, ABKHAZIAN, AFAR, ...
Does node-cld support languages as cld2 ?

**Comment by dachev** [comment] 2016-03-22 18:22
@henrycaohao Thanks for reporting this. Can you give me a little more information about your environment .Specifically:

* OS name and version
* Compiler name and version
* Node version
* npm version
* The command you used to run the tests

**Comment by henrycaohao** [comment] 2016-03-23 02:15
My environment:

- Windows 8.1 Enterprise 64-bit (Build 9600)
- Command prompt
- Node: v0.12.7
- Npm: v2.11.3
- Command: npm test

**Comment by dachev** [comment] 2016-06-05 18:35
@henrycaohao The windows build hasn't received mush love from me lately but I am intending to fix that in the upcoming months. Sorry for the delay and thank you for the patience.

**Comment by dachev** [comment] 2020-03-06 10:15
Closing this as a duplicate of #44. It will be fixed when we upgrade to CLD 3.

**Closed by dachev** 2020-03-06 10:15 UTC
Labels: windows
