### ISSUE TITLE
Error: `make` failed with exit code: 2

### ISSUE THREAD

**Issue by musichen** [dachev/node-cld#25] opened 2015-10-01 14:27 UTC
Trying to run cld on  Elementary OS Luna  (build on Ubuntu 12.04 Precise)  

During npm install cld  I get this error:

 CXX(target) Release/obj.target/cld/src/constants.o
clang: warning: argument unused during compilation: '-fno-tree-vrp'
  CXX(target) Release/obj.target/cld/src/cld.o
clang: warning: argument unused during compilation: '-fno-tree-vrp'
  SOLINK_MODULE(target) Release/obj.target/cld.node
clang: error: no such file or directory: 'muldefs'
make: *** [Release/obj.target/cld.node] Error 1
make: Leaving directory `/home/musichen/dev/bitbucket/wng-backend-langdetect/node_modules/cld/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.11.0-26-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/musichen/dev/bitbucket/wng-backend-langdetect/node_modules/cld
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Linux 3.11.0-26-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! cld@2.4.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cld@2.4.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the cld package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls cld
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/musichen/dev/bitbucket/wng-backend-langdetect/npm-debug.log

**Comment by dachev** [comment] 2016-02-07 11:50
@musichen It looks like you are using the Clang compiler on your machine. Can you confirm that?

**Comment by dachev** [comment] 2016-03-05 11:13
I tried reproducing this with Elementary OS Luna to no avail. Installation completed successfully with both g++ and clang. Absent of any further details I'm going to assume this was caused by a misconfigured environment and close this ticket.

**Closed** 2016-03-06 04:19 UTC
