### ISSUE TITLE
Error at npm install

### ISSUE THREAD

**Issue by MatiasPi** [dachev/node-cld#41] opened 2017-10-25 00:09 UTC
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "E:\\Programs\\nodejs\\node.exe" "E:\\Programs\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @paulcbetts/cld@2.4.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @paulcbetts/cld@2.4.6 install script 'node-gyp rebuild'. npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @paulcbetts/cld package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with: npm ERR!     npm bugs @paulcbetts/cld
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @paulcbetts/cld
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Documents\Electron projects\spellcheck examples\electron-spellchecker\npm-debug.log

[npm-debug.log](https://github.com/dachev/node-cld/files/1412860/npm-debug.log)

**Comment by apaatsio** [comment] 2017-11-08 15:16
I had a similar error. I believe it is caused by this: https://github.com/nodejs/node-gyp/pull/1267

You need to wait for a new release of node-gyp for the fix. The bug exists still in 3.6.2. Next version seems to be 4.0.0.

**Comment by Nokel81** [comment] 2018-03-12 20:43
This is odd because `2.4.7` installs fine on my Mac with node v8.10 but fails on Ubuntu with node v8.10

**Comment by dachev** [comment] 2020-03-06 10:11
This should be fixed in 2.6.0

**Closed by dachev** 2020-03-06 10:11 UTC
Labels: windows
